<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RetakesAllocator</RootNamespace>
      <OutputPath>$(SolutionDir)build\addons\counterstrikesharp\plugins\RetakesAllocator\</OutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MySqlConnector">
       <HintPath>MySqlConnector.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**" />
    <EmbeddedResource Remove="tests\**" />
    <None Remove="tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.232" />
    <PackageReference Include="RetakesPluginShared" Version="2.0.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
  </ItemGroup>
</Project>
