#!/usr/bin/env python3
"""
Scaffold a PanoramaManager layout and stylesheet.

    python3 new_layout.py mymenu                    # 10-row list, into ./panorama/
    python3 new_layout.py shop --rows 6 --out path/to/addon

Writes panorama/layout/custom_game/<name>.xml and panorama/styles/custom_game/<name>.css, then
tells you what the plugin side has to say to drive it.

WHY SCAFFOLD RATHER THAN COPY. A layout that implements LayoutContract has to agree with the C# on
every id - row3_btn, row3_title, menu_page - and one typo produces a row that renders and does
nothing, with no error anywhere. Generating both sides from the same list removes that class of bug.
"""
from __future__ import annotations

import argparse
import pathlib
import sys

LAYOUT = '''<root>
	<styles>
		<include src="s2r://panorama/styles/custom_game/hud_shared.vcss_c" />
		<include src="s2r://panorama/styles/custom_game/{name}.vcss_c" />
	</styles>

	<!--
		{title}

		Implements LayoutContract with RowCount = {rows}. The pool size IS the page size: the library
		paginates past it, so a longer list is more pages rather than more rows.

		The root deliberately has NO id - the compiler rejects one there - and carries "hidden" so a
		spawned entity does not render an empty card to every player on the server before anyone
		opens it.

		DRIVEN BY:
		  menu_title / menu_subtitle   {{s:}}   - header
		  row{{n}}                       hidden - unused rows collapse, leaving no gap
		  row{{n}}_title / row{{n}}_sub    {{s:}}   - row text
		  row{{n}}_btn                   click  - MenuItem.OnSelect
		  menu_close                   click  - closes
		  menu_page / nav_prev / nav_next     - pager, shown when has-pages is set
		  menu_footer                  {{s:}}   - status line
	-->
	<Panel class="hud-screen" hittest="false">
		<Panel id="PanoramaRoot" class="hud-root hud-card {name}-root hidden">

			<Panel class="hud-head">
				<Label class="hud-title" text="{{s:menu_title}}" />
				<Label class="hud-tag" text="{{s:menu_subtitle}}" />
				<Button id="menu_close" class="hud-exit">
					<Label class="hud-x" text="&#x2715;" />
				</Button>
			</Panel>

			<Panel class="{name}-rows">
{rows_xml}
			</Panel>

			<Panel class="{name}-nav">
				<Button id="nav_prev" class="{name}-nav-btn">
					<Label class="{name}-nav-lbl" text="&#x2039;" />
				</Button>
				<Label class="{name}-page" text="{{s:menu_page}}" />
				<Button id="nav_next" class="{name}-nav-btn">
					<Label class="{name}-nav-lbl" text="&#x203a;" />
				</Button>
			</Panel>

			<Panel class="hud-foot">
				<Label class="hud-hint" text="{{s:menu_footer}}" />
			</Panel>

		</Panel>
	</Panel>
</root>
'''

ROW = '''				<Panel id="row{i}" class="{name}-row hidden">
					<Button id="row{i}_btn" class="{name}-row-hit">
						<Label class="{name}-row-title" text="{{s:row{i}_title}}" />
						<Label class="{name}-row-sub" text="{{s:row{i}_sub}}" />
					</Button>
				</Panel>'''

STYLE = '''/*
    {name} - generated by new_layout.py.

    The card, header, footer and reveal come from hud_shared. Only what is specific to this menu
    belongs here.

    PANORAMA IS NOT THE WEB. No display, no flex, no calc(), no rgb(). box-shadow takes the colour
    first. background-size takes "contains", not "contain". A child at width:100% inside a parent
    with no width renders as nothing. Check any unfamiliar property against the reference before
    using it - an unregistered one is dropped silently.
*/

.{name}-root {{
    width: 460px;
}}

.{name}-rows {{
    flow-children: down;
    width: 100%;
    padding: 10px 14px;
}}

.{name}-row {{
    width: 100%;
    margin-bottom: 4px;
}}

.{name}-row-hit {{
    flow-children: down;
    width: 100%;
    padding: 9px 12px;
    border-left: 2px solid #ffffff14;
    background-color: #ffffff0a;
    transition-property: background-color, border-color;
    transition-duration: 0.1s;
    transition-timing-function: ease-in-out;
}}

.{name}-row-hit:hover {{
    background-color: #ffffff16;
    border-left-color: #f0a531;
}}

.{name}-row.disabled {{ opacity: 0.35; }}

.{name}-row-title {{
    width: 100%;
    font-family: Stratum2;
    font-size: 13px;
    color: #ffffff;
}}

.{name}-row-sub {{
    width: 100%;
    font-family: Stratum2 Mono;
    font-size: 10px;
    color: #6b737c;
    text-overflow: ellipsis;
    margin-top: 2px;
}}

/* Hidden until the server sets has-pages on the root, which it does only when PageCount > 1. */
.{name}-nav {{
    flow-children: right;
    width: 100%;
    padding: 4px 14px 8px 14px;
    horizontal-align: center;
    visibility: collapse;
}}

.{name}-root.has-pages .{name}-nav {{ visibility: visible; }}

.{name}-nav-btn {{
    width: 24px;
    height: 22px;
    margin: 0px 3px;
    background-color: #ffffff08;
    vertical-align: center;
}}

.{name}-nav-btn:hover {{ background-color: #ffffff16; }}

.{name}-nav-lbl {{
    width: 100%;
    font-size: 13px;
    color: #9aa2ac;
    text-align: center;
    vertical-align: center;
}}

.{name}-page {{
    font-family: Stratum2 Mono;
    font-size: 11px;
    color: #6b737c;
    vertical-align: center;
    margin: 0px 8px;
}}
'''

USAGE = '''
Drive it from your plugin:

    Panorama.Init(this);

    var menu = Panorama.Spawn("panorama/layout/custom_game/{name}.vxml_c",
                              new LayoutContract {{ RowCount = {rows} }});

    menu.Title = "{title}";
    menu.SetItems(items.Select(i => new MenuItem(
        Id:       i.Id,
        Title:    i.Name,
        Subtitle: i.Detail,
        OnSelect: e => Handle(e.Player, i))));

    menu.Open(player);

Then:

    python3 validate.py            # before every compile
    python3 preview.py {layout} {rows}
'''


def main() -> int:
    ap = argparse.ArgumentParser(description="Scaffold a PanoramaManager layout.")
    ap.add_argument("name", help="lowercase, no spaces - becomes the file name and class prefix")
    ap.add_argument("--rows", type=int, default=10, help="row pool size, which is also the page size")
    ap.add_argument("--out", default=".", help="directory containing (or to contain) panorama/")
    args = ap.parse_args()

    name = args.name.strip().lower().replace(" ", "_").replace("-", "_")

    if not name.isidentifier():
        print(f"'{args.name}' is not usable as a file and class prefix")
        return 2

    if args.rows < 1:
        print("--rows must be at least 1")
        return 2

    root       = pathlib.Path(args.out).resolve()
    layout_dir = root / "panorama" / "layout" / "custom_game"
    style_dir  = root / "panorama" / "styles" / "custom_game"
    layout     = layout_dir / f"{name}.xml"
    style      = style_dir / f"{name}.css"

    # Refuse rather than overwrite: a layout is hand-tuned after generation, and clobbering one is
    # not something a scaffold should ever do silently.
    for existing in (layout, style):
        if existing.exists():
            print(f"{existing} already exists - delete it or pick another name")
            return 1

    layout_dir.mkdir(parents=True, exist_ok=True)
    style_dir.mkdir(parents=True, exist_ok=True)

    rows_xml = "\n".join(ROW.format(i=i, name=name) for i in range(args.rows))
    title    = name.replace("_", " ").title()

    layout.write_text(LAYOUT.format(name=name, rows=args.rows, rows_xml=rows_xml, title=title))
    style.write_text(STYLE.format(name=name))

    print(f"wrote {layout}")
    print(f"wrote {style}")
    print(USAGE.format(name=name, rows=args.rows, title=title, layout=layout))

    return 0


if __name__ == "__main__":
    sys.exit(main())
